# Generated by Django 5.0.6 on 2025-11-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_country_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
