# Generated by Django 5.0.6 on 2025-11-04 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/photos/')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['plate'],
                'unique_together': {('user', 'plate')},
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.CharField(max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_day', models.PositiveSmallIntegerField()),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='cars.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SOAT', 'SOAT'), ('Tecnomecanica', 'Tecnomecánica'), ('Insurance', 'Insurance'), ('Registration', 'Registration')], max_length=30)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='cars/documents/')),
                ('notes', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cars.car')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('concept', models.CharField(max_length=150)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('workshop', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='cars/maintenance/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='cars.car')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
