# Generated by Django 5.0.6 on 2025-11-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_document_ai_checked_at_document_ai_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_license_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='license_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='license_validation_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
