# Generated by Django 5.0.6 on 2025-11-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_document_is_license_valid_document_license_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='external_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='external_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='document',
            name='external_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
