# Generated by Django 5.0.6 on 2025-11-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_document_external_fetched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
