# Generated by Django 5.0.6 on 2025-11-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_document_expiry_date_alter_document_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImageCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color_key', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='cars/gallery/')),
            ],
            options={
                'ordering': ['brand', 'model'],
                'unique_together': {('brand', 'model', 'color_key')},
            },
        ),
    ]
